CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''), 
    done BOOLEAN,
    projectId INTEGER REFERENCES projects(id)
);

INSERT INTO projects(name, priority, descripction, deliverydate)
    VALUES('Make a web app', 1, 'Using Javascript', '2019-05-12');

INSERT INTO projects(name, priority, descripction, deliverydate)
    VALUES('Make an app', 1, 'Using Dart', '2019-05-13');

INSERT INTO projects(name, priority, descripction, deliverydate)
    VALUES('Make a Desktop app', 2, 'Using C++', '2019-05-14');

-- INSERT TASKS DATA

INSERT INTO tasks(name, done, projectId)
    VALUES('Download Vue.js', false, 1);

INSERT INTO tasks(name, done, projectId)
    VALUES('Create UI web', false, 1);

INSERT INTO tasks(name, done, projectId)
    VALUES('Download Flutter', false, 2);

INSERT INTO tasks(name, done, projectId)
    VALUES('Design UI', false, 2);